# Generated by Django 2.2.7 on 2020-04-10 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Geotest', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Pages',
        ),
    ]
