# Generated by Django 2.2.7 on 2020-04-11 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Geotest', '0002_auto_20200410_1801'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pages',
            new_name='Page',
        ),
    ]
