# Generated by Django 2.2.7 on 2020-04-11 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Geotest', '0003_auto_20200411_1326'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Page',
            new_name='Ort',
        ),
    ]
